### ISSUE TITLE
Remove virion data from globi?

### ISSUE THREAD

**Issue by tpoisot** [globalbioticinteractions/virion#1] opened 2022-01-13 20:47 UTC
Hi @jhpoelen - I wanted to bring the following caveat from the latest version of VIRION (the stable one) to your attention:

> To ensure that one stable (raw) version of VIRION remains the database of record, we ask that you do not reproduce VIRION into other databases or include static copies as supplement to publications. If you develop improved versions with taxonomic corrections or new data sources added, please contact us so we can work together to keep improving the main VIRION database!

Do you know which version you are currently indexing?

**Comment by jhpoelen** [comment] 2022-01-13 20:58
@tpoisot thanks for your message.

Here's the signature of the virion version currently indexed by GloBI. 

globalbioticinteractions/virion	https://github.com/viralemergence/virion/raw/main/Virion/Virion.csv.gz	825ac1de281be3803a38839b5a0cd48697dba2d3c2d508af7d149c775dcf071c	2022-01-08T05:07:40.862Z

The resource is updated whenever the source file changes.

Note that 825ac1de281be3803a38839b5a0cd48697dba2d3c2d508af7d149c775dcf071c is the sha256 hash of the referenced file.

**Comment by cjcarlson** [comment] 2022-01-13 21:19
I'll just +1 Tim's request. I would strongly suggest (request) de-indexing. The rationale, on our end, is

1. VIRION is designed to be internally taxonomically-consistent. (Sort of a slightly different goal than GLOBI: you guys are going for comprehensive, we're going for harmonized.) When it's propagated into other databases, it goes from harmonized product to another layer of raw data with internal conflicts with other raw data. Someone could download VIRION through GLOBI and get ten different named versions of the same species interactions - and they can't, really, in VIRION. So it inherently reduces the quality of the dataset.

2.  Our group is trying to move people away from out-of-the-box analyses of _any_ host virus-dataset without careful curation, and the manuscript that accompanies VIRION details how to use VIRION as a starting point, not a ready-to-use data product, as such. We ask people not to reproduce the data because we don't really want anyone to access these data in a setting where the expectation doesn't exist that they will see those instructions. This is particularly important because, for example, public health decisions might be made over something as simple as whether or not a particular virus is reported to infect humans, or cullings / conservation decisions might be informed by whether particular species are reported to host a zoonotic virus. 

3.  Particularly as the study isn't even out in a non-preprint form yet, we would prefer people to respect the massive investment of the ECRs who put this dataset together and ensure people go to the source, read the guidelines, and cite this source!

We've spent quite a lot of time debating whether we think this is the right way to walk this tightrope, but it's where we've landed - I hope all of that makes sense.

**Comment by cjcarlson** [comment] 2022-01-13 21:20
As a final p.s., I'll add that we've tried to take this kind of thing seriously, in reverse, when we put VIRION together. For example, EID2 can't be accessed in an updating way without scraping right now, and that team asks end users not to scrape. So, it's not indexed that way in VIRION. I don't see this at odds with open science - quite the opposite, it's about fostering a constructive ecosystem! :)

**Comment by cjcarlson** [comment] 2022-01-13 21:23
As a final p.p.s., if you want any help indexing the component datasets of VIRION into GLOBI directly - e.g., making sense of the PREDICT database - I'd be more than happy to throw some hours at that in a few weeks (going on a small vacation). You guys already capture the other direct source of updating data (GenBank), so your marginal gain from VIRION is, well, marginal!

**Comment by cjcarlson** [comment] 2022-01-14 00:55
You and @kephelps have convinced me. https://github.com/viralemergence/virion/commit/c1c37eb885a45129f06ecb662e6f8df90d771ed1

I'm still happy to throw in a few more million lines of code and help you guys index the source datasets instead. But open is open.

**Comment by jhpoelen** [comment] 2022-02-04 17:16
see also related tweets - 

https://twitter.com/GlobalBiotic/status/1481737750877327363

**Comment by cjcarlson** [comment] 2022-02-06 05:08
Jorrit, I think you can close this out - like I said three weeks ago, you guys convinced me, and I changed the readme.

**Comment by jhpoelen** [comment] 2022-02-06 18:52
@cjcarlson excellent! thanks for the reminder, closing issue.

**Closed as completed by jhpoelen** 2022-02-06 18:52 UTC
